#!/bin/bash

echo "Running postinstall script"

# load our daemon using launchctl 2.0 syntax

if launchctl print system/edu.asu.jmc.shutdown-hook; then
    launchctl enable system/edu.asu.jmc.shutdown-hook
    launchctl kickstart system/edu.asu.jmc.shutdown-hook
else
    launchctl load -w /Library/LaunchDaemons/edu.asu.jmc.shutdown-hook.plist
fi

exit 0
